server:
  port: 8888
spring:
  profiles:
    active:
    - dev
  cloud:
    config:
      server:
        git:
          search-paths:
          - /config
          timeout: 60000 # default is 5000 ms
         